"""Built-in config sources. kill_pv2 AI adds more via Tavily discovery; admins via /source_add.

Kinds:
  sub  -> base64 or plain subscription text
  raw  -> plain text with links (GitHub raw)
  html -> any web page (links are regex-extracted from the HTML)
  tg   -> public Telegram channel preview page (https://t.me/s/<channel>)
"""

BUILTIN_SOURCES: list[tuple[str, str]] = [
    # --- large aggregators (GitHub raw) ---
    ("https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_Sub.txt", "sub"),
    ("https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/All_Configs_base64_Sub.txt", "sub"),
    ("https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/subscriptions/v2ray/all_sub.txt", "sub"),
    ("https://raw.githubusercontent.com/MatinGhanbari/v2ray-configs/main/subscriptions/v2ray/super-sub.txt", "sub"),
    ("https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge.txt", "sub"),
    ("https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_base64.txt", "sub"),
    ("https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/Eternity.txt", "sub"),
    ("https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/airport_sub_merge.txt", "sub"),
    ("https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/sub.txt", "sub"),
    ("https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/server.txt", "sub"),
    ("https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/splitted/mixed", "sub"),
    ("https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/vless", "sub"),
    ("https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/vmess", "sub"),
    ("https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/trojan", "sub"),
    ("https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/ss", "sub"),
    ("https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/main/submerge/converted.txt", "sub"),
    ("https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/mix", "sub"),
    ("https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vless", "sub"),
    ("https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/vmess", "sub"),
    ("https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector/main/sub/trojan", "sub"),
    ("https://raw.githubusercontent.com/MhdiTaheri/V2rayCollector_Py/main/sub/Mix/mix.txt", "sub"),
    ("https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/mix.txt", "sub"),
    ("https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/vless.txt", "sub"),
    ("https://raw.githubusercontent.com/Kwinshadow/TelegramV2rayCollector/main/sublinks/vmess.txt", "sub"),
    ("https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/vless", "sub"),
    ("https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/ss", "sub"),
    ("https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/tr", "sub"),
    ("https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/v2", "sub"),
    ("https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.txt", "sub"),
    ("https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list_raw.txt", "sub"),
    ("https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub", "sub"),
    ("https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/v2ray.txt", "sub"),
    ("https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/v2ray.txt", "sub"),
    ("https://raw.githubusercontent.com/freefq/free/master/v2", "sub"),
    ("https://raw.githubusercontent.com/ripaojiedian/freenode/main/sub", "sub"),
    ("https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription_num", "sub"),
    ("https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription1", "sub"),
    ("https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription2", "sub"),
    ("https://raw.githubusercontent.com/w1770946466/Auto_proxy/main/Long_term_subscription3", "sub"),
    ("https://raw.githubusercontent.com/vxiaov/free_proxies/main/links.txt", "sub"),
    ("https://raw.githubusercontent.com/ts-sf/fly/main/v2", "sub"),
    ("https://raw.githubusercontent.com/Mosifree/-FREE2CONFIG/refs/heads/main/T,H", "sub"),
    ("https://raw.githubusercontent.com/Mosifree/-FREE2CONFIG/refs/heads/main/Vmess", "sub"),
    ("https://raw.githubusercontent.com/youfoundamin/V2rayCollector/main/mixed_iran.txt", "sub"),
    ("https://raw.githubusercontent.com/Rayan-Config/C-Sub/refs/heads/main/configs/proxy.txt", "sub"),
    ("https://raw.githubusercontent.com/MrPooyaX/SansorchiFucker/main/data.txt", "sub"),
    ("https://raw.githubusercontent.com/4n0nymou3/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs.txt", "sub"),
    ("https://raw.githubusercontent.com/AzadNetCH/Clash/main/AzadNet.txt", "sub"),
    ("https://raw.githubusercontent.com/mheidari98/.proxy/main/all", "sub"),
    ("https://raw.githubusercontent.com/mheidari98/.proxy/main/vmess", "sub"),
    ("https://raw.githubusercontent.com/mheidari98/.proxy/main/vless", "sub"),
    ("https://raw.githubusercontent.com/mheidari98/.proxy/main/trojan", "sub"),
    ("https://raw.githubusercontent.com/LalatinaHub/Mineral/master/result/nodes", "sub"),
    ("https://raw.githubusercontent.com/HosseinKoofi/GO_V2rayCollector/main/mixed_iran.txt", "sub"),
    ("https://raw.githubusercontent.com/shabane/kamaji/master/hub/merged.txt", "sub"),
    ("https://raw.githubusercontent.com/shabane/kamaji/master/hub/b64/merged.txt", "sub"),
    ("https://raw.githubusercontent.com/V2RayRoot/V2RayConfig/main/Config/vless.txt", "sub"),
    ("https://raw.githubusercontent.com/V2RayRoot/V2RayConfig/main/Config/vmess.txt", "sub"),
    ("https://raw.githubusercontent.com/V2RayRoot/V2RayConfig/main/Config/trojan.txt", "sub"),
    ("https://raw.githubusercontent.com/V2RayRoot/V2RayConfig/main/Config/shadowsocks.txt", "sub"),
    ("https://raw.githubusercontent.com/SoliSpirit/v2ray-configs/main/all_configs.txt", "sub"),
    ("https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/default.txt", "sub"),
    ("https://raw.githubusercontent.com/ndsphonemy/proxy-sub/main/speed.txt", "sub"),
    ("https://raw.githubusercontent.com/mehran1404/Sub_Link/main/V2RAY-Sub.txt", "sub"),
    ("https://raw.githubusercontent.com/Mahdi0024/ProxyCollector/master/sub/proxies.txt", "sub"),
    ("https://raw.githubusercontent.com/ebrasha/free-v2ray-public-list/main/all_extracted_configs.txt", "sub"),
    ("https://raw.githubusercontent.com/Proxydaemitelegram/Proxydaemi44/main/Proxydaemi44", "sub"),
    ("https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vless.txt", "sub"),
    ("https://raw.githubusercontent.com/Mohammadgb0078/IRV2ray/main/vmess.txt", "sub"),
    ("https://raw.githubusercontent.com/awesome-vpn/awesome-vpn/master/all", "sub"),
    ("https://raw.githubusercontent.com/NiREvil/vless/main/sub/SSTime", "sub"),
    # --- web pages ---
    ("https://robin.nscl.ir", "html"),
    ("https://v2.alicivil.workers.dev/?list=3000&start=1", "html"),
    ("https://shadowmere.xyz/api/b64sub", "sub"),
    # --- Telegram channels (public preview) ---
    ("https://t.me/s/v2ray_configs_pool", "tg"),
    ("https://t.me/s/V2rayNGn", "tg"),
    ("https://t.me/s/v2rayng_fast", "tg"),
    ("https://t.me/s/ConfigsHUB", "tg"),
    ("https://t.me/s/PrivateVPNs", "tg"),
    ("https://t.me/s/DirectVPN", "tg"),
    ("https://t.me/s/VlessConfig", "tg"),
    ("https://t.me/s/v2rayNG_Matsuri", "tg"),
    ("https://t.me/s/proxystore11", "tg"),
    ("https://t.me/s/vmessorg", "tg"),
    ("https://t.me/s/v2ray_outlineir", "tg"),
    ("https://t.me/s/v2rayngvpn", "tg"),
    ("https://t.me/s/iP_CF", "tg"),
    ("https://t.me/s/Outline_Vpn", "tg"),
    ("https://t.me/s/napsternetv_config", "tg"),
    ("https://t.me/s/mftizi", "tg"),
    ("https://t.me/s/freewireguard", "tg"),
    ("https://t.me/s/V2RayTz", "tg"),
    ("https://t.me/s/forwardv2ray", "tg"),
    ("https://t.me/s/Helix_Servers", "tg"),
    ("https://t.me/s/VmessProtocol", "tg"),
    ("https://t.me/s/v2ray1_ng", "tg"),
    ("https://t.me/s/ShadowProxy66", "tg"),
    ("https://t.me/s/Lockey_vpn", "tg"),
    ("https://t.me/s/DailyV2RY", "tg"),
    ("https://t.me/s/FreakConfig", "tg"),
    ("https://t.me/s/proxy_mtm", "tg"),
    ("https://t.me/s/V2pedia", "tg"),
    ("https://t.me/s/vpn_ioss", "tg"),
    ("https://t.me/s/MsV2ray", "tg"),
    ("https://t.me/s/customv2ray", "tg"),
    ("https://t.me/s/nufilter", "tg"),
    ("https://t.me/s/ArV2ray", "tg"),
    ("https://t.me/s/UnlimitedDev", "tg"),
    ("https://t.me/s/VPNCUSTOMIZE", "tg"),
    ("https://t.me/s/V2rayCollectorDonate", "tg"),
    ("https://t.me/s/Parsashonam", "tg"),
    ("https://t.me/s/NIM_VPN_ir", "tg"),
    ("https://t.me/s/SafeNet_Server", "tg"),
    ("https://t.me/s/ViProxys", "tg"),
    ("https://t.me/s/Fr33C0nfig", "tg"),
    ("https://t.me/s/v2rayng_config_amin", "tg"),
    ("https://t.me/s/VPN_Z2", "tg"),
    ("https://t.me/s/Anty_Filter", "tg"),
    ("https://t.me/s/Vpnstable", "tg"),
    ("https://t.me/s/freenettoday", "tg"),
    ("https://t.me/s/vpnfail_v2ray", "tg"),
    ("https://t.me/s/Ryan_Config", "tg"),
    ("https://t.me/s/ConfigsHUB2", "tg"),
    ("https://t.me/s/XsV2ray", "tg"),
    ("https://t.me/s/v2rayvpn2", "tg"),
    ("https://t.me/s/VPNCLUBir", "tg"),
    ("https://t.me/s/FreeV2rays", "tg"),
    ("https://t.me/s/v2ray_swhil", "tg"),
    ("https://t.me/s/Server_Nekobox", "tg"),
    ("https://t.me/s/vpnowl", "tg"),
    ("https://t.me/s/iranbaxvpn", "tg"),
    ("https://t.me/s/MehradLearn", "tg"),
    ("https://t.me/s/vpn_tehran", "tg"),
    ("https://t.me/s/free_v2rayyy", "tg"),
    ("https://t.me/s/configV2rayNG", "tg"),
    ("https://t.me/s/OutlineVpnOfficial", "tg"),
    ("https://t.me/s/WomanLifeFreedomVPN", "tg"),
    ("https://t.me/s/V2rayNG3", "tg"),
    ("https://t.me/s/ZEDMODEONFIRE", "tg"),
    ("https://t.me/s/DeamNet_Proxy", "tg"),
    ("https://t.me/s/vpn_xw", "tg"),
    ("https://t.me/s/v2rayng_vpnrog", "tg"),
    ("https://t.me/s/Capoit", "tg"),
    ("https://t.me/s/Hope_Net", "tg"),
    ("https://t.me/s/TrustVPN_ir", "tg"),
    ("https://t.me/s/VPN_Official_ir", "tg"),
    ("https://t.me/s/PROXY_V2RAYNG", "tg"),
    ("https://t.me/s/Awlix_ir", "tg"),
    ("https://t.me/s/sinavm", "tg"),
    ("https://t.me/s/SRCVPN", "tg"),
    ("https://t.me/s/Proxy_PJ", "tg"),
    ("https://t.me/s/v2ray_vpn_ir", "tg"),
    ("https://t.me/s/VPNHUBEUR", "tg"),
    ("https://t.me/s/iTV2RAY", "tg"),
    ("https://t.me/s/mitivpn", "tg"),
    ("https://t.me/s/MTProtoProxies2", "tg"),
    ("https://t.me/s/fnet00", "tg"),
    ("https://t.me/s/Entry_net", "tg"),
    ("https://t.me/s/Proxy_Kavosh", "tg"),
]

# Tavily queries kill_pv2 AI uses to discover brand-new sources
DISCOVERY_QUERIES = [
    "free v2ray subscription github raw All_Configs_Sub.txt",
    "vless reality free config telegram channel iran",
    "v2ray configs collector github raw mixed",
    "free vmess vless trojan subscription link updated daily",
    "کانفیگ v2ray رایگان کانال تلگرام",
    "hysteria2 tuic free config list github",
    "shadowsocks free nodes github raw sub",
    "v2rayng free server iran 2026",
    "free proxy configs telegram t.me/s v2ray",
    "github v2ray-configs base64 sub raw.githubusercontent.com",
]
